project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!development/"
    - "!renv/"

embed-resources: true

website:
  title: "POPCORN-NCD"
  repo-url: "https://github.com/big-life-lab/popcorn-web"

  navbar:
    logo: assets/logo-PNG/popcorn-white_icon-white.png
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      # - text: Team
      #   href: team.qmd

    tools:
      - icon: github
        href: "https://github.com/big-life-lab/popcorn-web"

format:
  html:
    theme:
      - flatly # https://bootswatch.com/flatly/
      - assets/popcorn.scss
      - assets/popcorn-web.scss
    code-tools: false
    toc: true
    include-in-header:
      - assets/icons.html

bibliography: references.bib
csl: assets/vancouver.csl
