name: build-docs-composite-action
runs:
  using: composite
  steps:
    - name: Install quarto
      uses: quarto-dev/quarto-actions/setup@v2
    - name: Install tinytex
      run: quarto install tool tinytex
      shell: bash
    - name: setup-r
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.4.3"
    - name: Install renv
      run: R -e 'install.packages("renv")'
      shell: bash
    - name: Restore R environment
      run: R -e 'renv::restore()'
      shell: bash
    - name: Render quarto
      run: quarto render
      shell: bash